config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path
from . import views


app_name = 'main'


urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('signin/', views.sign_in, name='signin'),
    path('signup/', views.sign_up, name='signup'),
    path('join/', views.join, name='join'),

    path('myinfo/', views.myinfo, name='myinfo'),
    path('class_rec_ver2/mbti', views.mbti, name='mbti'),
    path('class_rec_ver2/keyword/', views.keyword, name='keyword'),
    path('class_rec_ver2/-keyword/', views.keyword, name='-keyword'),

    path('logout/', views.logout, name='logout'),
    path('classrec/', views.classrec, name='classrec'),
    path('upload-csv/', views.profile_upload, name="profile_upload"),
    path('myclass/', views.myclass, name='myclass'),
    path('class_rec_ver2/wish/<int:id>/', views.wish, name='wish'),
    path('myclass/-wish/<int:id>/', views.delete_wish, name='-wish'),
    path('classrec/subject/<int:id>/', views.subject, name='subject'),
    path('myclass/subject_/<int:id>/', views.subject_, name='subject_'),
    path('myclass/-subject/<int:id>/', views.delete_subject, name='-subject'),
    
    path('search_subject', views.search_subject, name='search_subject'),
    path('about', views.about, name='about'),
    path('class_rec_ver2', views.class_rec_ver2, name='class_rec_ver2'),
    path('my_class_ver2', views.my_class_ver2, name='my_class_ver2'),
    path('pre_lec_ver2', views.pre_lec_ver2, name='pre_lec_ver2'),
    path('my_class_ver2/pre_lec/delete', views.pre_lec_delete, name='pre_lec_delete'),
    path('my_class_ver2/save_lec/delete', views.save_lec_delete, name='save_lec_delete'),
]

main/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import UserManager
from django.db import models


# Create your models here.
class User(AbstractBaseUser):
    userid = models.TextField(max_length=20) # 계정
    username = models.TextField(max_length=20)
    user_number = models.TextField(max_length=10)
    mbti = models.TextField(max_length=4)

    objects = UserManager()

    USERNAME_FIELD = 'userid'
    REQUIRED_FIELDS = ['user_number']

    def __str__(self):
        return self.username


class Subject(models.Model):
    subj_id = models.IntegerField(unique=True)
    subj_name = models.TextField(max_length=20)
    category1 = models.TextField(max_length=10)
    category2 = models.TextField(max_length=10)
    prof_name = models.TextField(max_length=10)
    grading = models.TextField(max_length=100)
    time = models.TextField(max_length=20)
    room = models.TextField(max_length=10)


class SubjectKeywords(models.Model):
    subj_id = models.IntegerField()
    keyword_id = models.IntegerField()
    value = models.IntegerField()


class SubjectKeyword(models.Model):
    keyword_id = models.IntegerField()
    keyword = models.TextField(max_length=10)


class UserKeyword(models.Model):
    user_id = models.IntegerField()
    keyword_id = models.IntegerField()
    keyword = models.TextField(max_length=10)
    flag = models.IntegerField()

class WishList(models.Model):
    user_id = models.IntegerField()
    subj_id = models.IntegerField()


class UserSubject(models.Model):
    user_id = models.IntegerField()
    subj_id = models.IntegerField()
    good = models.IntegerField()
    rating = models.FloatField()

main/views.py
import csv
import io
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import euclidean_distances
import sklearn
from scipy.spatial.distance import squareform
from scipy.spatial.distance import pdist, jaccard
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.urls import reverse
from django.core.paginator import Paginator
import json
from . import apps
from .models import *
'''import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Embedding, Dot, Add, Flatten
from tensorflow.keras.layers import Dense, Concatenate, Activation
from tensorflow.keras.regularizers import l2
from tensorflow.keras.optimizers import SGD, Adamax'''


model = None
mu = 0

# Create your views here.
def index(request):
    return render(request, 'main/index.html')


def login(request):
    try:
        request.session['userid']
        return HttpResponseRedirect(reverse('main:class_rec_ver2'))
    except:
        return render(request, 'main/login.html')


def sign_in(request):
    global model, mu
    user_id = request.POST['user_id']
    user_pw = request.POST['user_pw']
    try:
        user = User.objects.get(userid=user_id, password=user_pw)
        request.session['userid'] = user_id
        '''if model is None: # 로그인 했을 때 모델이 비어있으면
            try:
                goods = list(UserSubject.objects.values_list('user_id', 'subj_id', 'good'))
                goods = [list(x) for x in goods]
                mbti = list(User.objects.values_list('id', 'mbti'))
                mbti = [list((x[0], int(x[1]))) for x in mbti]

                goods = pd.DataFrame(goods, columns=["id", "lecture", "rating"])
                mbti = pd.DataFrame(mbti, columns=["id", "mbti"])

                print(goods)
                print(mbti)

                mu = goods.rating.mean()  # 학습 데이터 평균
                cat_NeuralMF_begin(goods, mbti, 200)
            except Exception as ex:
                print(ex)'''
        return HttpResponseRedirect(reverse('main:class_rec_ver2'))
    except User.DoesNotExist:
        return HttpResponse('실패')


def sign_up(request):
    return render(request, 'main/signup.html')


def join(request):
    user_id = request.POST['id']
    user_pw = request.POST['pw']
    user_name = request.POST['name']
    user_number = request.POST['student_number']
    try:
        user = User.objects.get(userid=user_id)
        return HttpResponse('이미 존재하는 아이디')
    except User.DoesNotExist:
        user = User(userid=user_id, password=user_pw, username=user_name, user_number=user_number, mbti='0')
        user.save()

        keywords = SubjectKeyword.objects.all()
        for keyword in keywords:
            UserKeyword.objects.update_or_create(
                user_id=user.id,
                keyword_id=keyword.keyword_id,
                keyword=keyword.keyword,
                flag=0
            )
        request.session['userid'] = user_id
        return HttpResponseRedirect(reverse('main:class_rec_ver2'))

    return HttpResponseRedirect(reverse('main:signup'))


def myinfo(request):
    try:
        user = User.objects.get(userid=request.session['userid'])
        user_keyword = []
        try:
            keywords = SubjectKeyword.objects.all()
            try:
                user_keyword = get_list_or_404(UserKeyword, user_id=user.id)
            except:
                pass
            if len(keywords) > len(user_keyword):
                for keyword in keywords:
                    try:
                        UserKeyword.objects.get(user_id=user.id, keyword_id=keyword.keyword_id)
                    except:
                        UserKeyword.objects.update_or_create(
                            user_id=user.id,
                            keyword_id=keyword.keyword_id,
                            keyword=keyword.keyword,
                            flag=0
                        )
                user_keyword = get_list_or_404(UserKeyword, user_id=user.id)
        except:
            pass
        return render(request, 'main/class_lec_ver2.html',
                      {'user': get_object_or_404(User, userid=request.session['userid']),
                       'user_keywords': user_keyword})
    except KeyError:
        return HttpResponseRedirect(reverse('main:index'))


def mbti(request):
    try:
        value = request.POST['hidden_mymbti']
        user = User.objects.get(userid=request.session['userid'])
        user.mbti = value
        user.save()
        return HttpResponseRedirect(reverse('main:class_rec_ver2'))
    except KeyError:
        return HttpResponseRedirect(reverse('main:class_rec_ver2'))


def keyword(request):
    try:
        user = User.objects.get(userid=request.session['userid'])
        if request.method == "POST":
            keyword_id = dict(json.loads(request.body.decode("utf-8")).items())['keyword_id']
            user_keyword = UserKeyword.objects.get(user_id=user.id, keyword_id=keyword_id)
            if user_keyword.flag == 0:
                user_keyword.flag = 1
            else:
                user_keyword.flag = 0
            user_keyword.save()
            return JsonResponse({
                'success': True, }, json_dumps_params={'ensure_ascii': True})
            # return HttpResponseRedirect(reverse('main:class_rec_ver2'))
    except KeyError:
        return JsonResponse({
            'success': False, }, json_dumps_params={'ensure_ascii': True})
        # return HttpResponseRedirect(reverse('main:class_rec_ver2'))


def pre_lec(data):
    data_wide = data.pivot_table(index=["id"],
                                 columns='keyword',
                                 values='value')
    data_wide = data_wide.fillna(0)

    return data_wide


def keyword_sort(user_keyword, lecture_bin):
    user_keyword = user_keyword.set_index("keyword")
    user_keyword_list = list(user_keyword.iloc[:, 0])
    check = lecture_bin * user_keyword_list
    result_list = check.sum(axis=1).sort_values(axis=0, ascending=False).index

    return result_list


def total_sim(like_data, wish_data, score_data, lecture_data, alpha):
    # like_in = pd.read_csv(file_path + "ratings_good.csv")
    # wish_in = pd.read_csv(file_path + "ratings_wish.csv")
    # score_in = pd.read_csv(file_path + "ratings_score.csv")
    # lecture_in = pd.read_csv(file_path + "lecture_bin.csv", encoding='cp949')

    like_in = pd.DataFrame(like_data, columns=["id", "lecture", "rating"])
    score_in = pd.DataFrame(score_data, columns=["id", "lecture", "rating"])
    lecture_in = pd.DataFrame(lecture_data, columns=["id", "keyword", "value"])

    # user_keyword = pd.DataFrame(a, columns=["keyword","key"])

    lecture_wide = pre_lec(lecture_in)
    lecture_list = lecture_wide.sort_values(axis=0, ascending=True, by="id").index
    # 혹시 몰라서 정렬함.

    like_wide = pre(like_in)
    score_wide = pre(score_in)

    like_sim = sim(like_wide, lecture_list)
    score_sim = sim(score_wide, lecture_list)
    # print(score_sim)
    lecture_sim = sim_lecture(lecture_wide, lecture_list)

    ts = like_sim * alpha[0] + score_sim * alpha[1] + lecture_sim * alpha[3]

    if len(wish_data) > 0:
        wish_in = pd.DataFrame(wish_data, columns=["id", "lecture"])
        wish_in["rating"] = 1
        wish_wide = pre(wish_in)
        wish_sim = sim_bin(wish_wide, lecture_list)
        ts += + wish_sim * alpha[2]

    """like_sim.to_csv("like_sim.csv")
    wish_sim.to_csv("wish_sim.csv")
    lecture_sim.to_csv("lecture_sim.csv")
    score_sim.to_csv("score_sim.csv")"""

    return ts, lecture_list


def pre(data):
    data_wide = data.pivot_table(index=["id"],
                                 columns='lecture',
                                 values='rating')
    data_wide = data_wide.fillna(0)

    return data_wide


def pre_lec(data):
    data_wide = data.pivot_table(index=["id"],
                                 columns='keyword',
                                 values='value')
    data_wide = data_wide.fillna(0)

    return data_wide


def sim(data_wide, lecture_list):
    # data_sim = sklearn.metrics.pairwise.cosine_similarity(data_wide.T, dense_output=True)
    # data_sim = pd.DataFrame(data_sim,index=list(data_wide),columns=list(data_wide))
    # data_sim = data_sim - np.eye(len(data_sim))

    data_sim = sklearn.metrics.pairwise_distances(data_wide.T, metric='cosine')
    data_sim = pd.DataFrame(data_sim, index=list(data_wide), columns=list(data_wide))

    data_sim = 1 - data_sim - np.eye(len(data_sim))
    data_sim = pd.DataFrame(data_sim, index=lecture_list, columns=lecture_list)
    data_sim = data_sim.fillna(0)

    # 데이터의 수가 희소하므로 표준화는 배제한다.
    # 표준화가 필요하다면 0을 제외하고 진행할 것. 4/9 와 9 가 있을 때, 4/9의 9가 더 작아질 위험이 있음.

    # euclidean_distance & 정규화
    """data_sim = euclidean_distances(data_wide.T,data_wide.T)
    data_sim = data_sim / data_sim.max(axis=0).max()
    data_sim = (data_sim - data_sim.min(axis=0).min()) / (data_sim.max(axis=0).max() - data_sim.min(axis=0).min())
    data_sim = 1 - data_sim - np.eye(len(data_sim))"""

    return data_sim


def sim_bin(data_wide, lecture_list):
    data_sim = 1 - pdist(data_wide.T, 'jaccard')
    data_sim = squareform(data_sim)

    data_sim = pd.DataFrame(data_sim, index=list(data_wide), columns=list(data_wide))
    data_sim = pd.DataFrame(data_sim, index=lecture_list, columns=lecture_list)
    data_sim = data_sim.fillna(0)

    return data_sim


def sim_lecture(lecture_wide, lecture_list):
    lecture_wide["sum"] = lecture_wide.sum(axis=1)
    lecture_wide_filtered = lecture_wide[lecture_wide['sum'] != 0]
    lecture_wide_filtered = lecture_wide_filtered.drop(['sum'], axis=1)
    # 후에 행 합계가 0인 경우 제거하는 함수 발견하면 수정할 것.

    data_sim = 1 - pdist(lecture_wide_filtered, 'jaccard')
    data_sim = squareform(data_sim)

main/templates/main/about.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main/css/about_style.css' %}">
    <link href="fonts.googleapis.com/earlyaccess/notosanskr.css" rel="stylesheet">
    <title>about</title>
</head>
<body>
    <div class="sidebar">
        <div class="about_title">
            About 강의추천시스템 by COSMIC
        </div>
        <img src="{% static 'main/img/cosmic_logo.png' %}">
    </div>
    <div class="about_container">

    한 학기 동안 듣는 강의,<br>
    나에게 딱 맞는 강의를 찾는 방법은 없을까?<br><br>

    다양한 키워드로<br>
    나에게 맞는,<br>
    내가 원하는 강의를<br>
    손쉽게, 한번에<br><br>

    사용자의 취향이 반영된 다양한 강의평가 데이터를 활용하고,<br>
    최신의 딥러닝 기술을 활용하여 다양한 강의를 추천합니다.<br>
    이때, 키워드와 선호도, 그리고 성적을 기반으로<br>
    사용자 각각에게 최적화 된 강의 추천 서비스를 제공합니다.<br><br>

    사용할수록<br>
    더 올라가는 정확도<br>
    딥러닝 알고리즘을 기반으로 하고 있기 때문에,<br>
    사용하면 할 수록 더 많은 데이터를 수집하게 됩니다.<br>
    따라서, 더 정확하게 분석하여 만족스러운 추천을 제공할 수 있습니다.<br>
    
    </div>
</body>
</html>

main/templates/main/add_rating.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

main/templates/main/add_subject.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>데이터 입력</title>
</head>
<body>
    <div>
        <form action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}
            <label for="file1" style="font-size:30px;"> DB에 강의 데이터 입력</label><br><br>
            <input type="file" id="file1" name="file1"><br><br>
            <button type="submit">입력</button>
        </form>
    </div><br>
    <div>
        <form action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}
            <label for="file2" style="font-size:30px;"> DB에 키워드 데이터 입력</label><br><br>
            <input type="file" id="file2" name="file2"><br><br>
            <button type="submit">입력</button>
        </form>
    </div><br>
    <div>
        <form action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}
            <label for="file3" style="font-size:30px;"> DB에 강의 키워드 데이터 입력</label><br><br>
            <input type="file" id="file3" name="file3"><br><br>
            <button type="submit">입력</button>
        </form>
    </div>
</body>
</html>

main/templates/main/easter.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main/css/signup_style.css' %}">
    <link href="fonts.googleapis.com/earlyaccess/notosanskr.css" rel="stylesheet">
    <title>easter</title>
</head>
<body>
    아무것도 없지롱~~ 

    
</body>
</html>

main/templates/main/my_class_ver2.html
{% load static %}
<html>
    <head>
        <title>COSMIC [class recommender system] My class</title>
        <LINK HREF="{% static 'main/css/my_classVer2.css' %}" rel="stylesheet" />
        <script src="{% static 'main/js/PreLecVer2.js' %}" ></script>
        <script src="{% static 'main/js/jquery-3.5.1.min.js'%}"></script>
        <script src="{% static 'main/js/jquery.csrf.js'%}"></script>
    </head>
    <body>
        <div class="all"> 
            <div class="menu_bar">
                <div class="profile">
                    <div class="profile_logo">
                        <img src="{% static 'main/img/main_logo.png' %}" width="40px" height='40px' >
                    </div>
                    <div class="profile_name">
                        <span style="font-size: 15px; font-weight: bold; ">{{ user.username }}</span><br>
                        <span style="font-size: 10px; font-weight: bold; opacity: 50; ">{{ user.user_number }}</span>
                    </div>
                    <div class="logout">
                        <a href="{% url 'main:logout' %}" >log out</a>
                    </div>
                </div>
        
                <ul class="menu_list" >
                    <li class="menu_button" >
                        <A href="{% url 'main:pre_lec_ver2' %}" >
                            <img src="{% static 'main/img/들었던강의.png' %}" width="200" height='40' >
                        </A>
                    </li>
                    <li class="menu_button">
                        <A href="{% url 'main:class_rec_ver2' %}"  >
                            <img src="{% static 'main/img/recommender.png' %}" width="200" height='40' >
                        </A>
                    </li>
                    <li class="menu_button_thisPage">
                        <A href="{% url 'main:my_class_ver2' %}" >
                            <img src="{% static 'main/img/my_class.png' %}" width="200" height='40' >
                        </A>
                    </li>   
                </ul>
        
            </div>

            <div class="container" >
                <div class="page_title">
                    <span style="font-size: 50px; font-weight: 900; ">My class</span>
                </div>
                <div class="content_container">
                    <div class="Pre_lecture_container">
                        <div class="Pre_lecture_title">
                            <span style="font-size: 25px; font-weight: bold; "> 들었던 강의</span>
                        </div>
                        {% csrf_token %}
                        {% for pre_lec in pre_lec_list %}
                            <div class="class_window" id='{{ pre_lec.subj_id }}'>
                                <div class="class_name_window">
                                    <span style="font-size: 25px; font-weight: bold; ">{{ pre_lec.subj_name}}</span><br>
                                    <span style="font-size: 15px; font-weight: bold; ">{{ pre_lec.prof_name}}</span><br>
                                </div> 
                                <div class="minus_button" id='pre_lec_minus_button' value='{{ pre_lec.subj_id }}'>
                                    <img src="{% static 'main/img/minus.png'%}" width="15" height="15">
                                </div>       
                            </div>
                        {% endfor %}
                       
                    </div>
                    <div class="save_lecture_container">
                        <div class="save_lecture_title">
                            <span style="font-size: 25px; font-weight: bold; "> 찜한 강의</span>
                        </div>
                        {% csrf_token %}
                        {% for save_lec in save_lec_list %}
                            <div class="class_window" id='{{ save_lec.subj_id }}'>
                                <div class="class_name_window">
                                    <span style="font-size: 25px; font-weight: bold; ">{{ save_lec.subj_name}}</span><br>
                                    <span style="font-size: 15px; font-weight: bold; ">{{ save_lec.prof_name}}</span><br>
                                </div> 
                                <div class="minus_button" id='save_lec_minus_button' value='{{ save_lec.subj_id }}'>
                                    <img src="{% static 'main/img/minus.png'%}" width="15" height="15">
                                </div>       
                            </div>
                        {% endfor %}
                        
                    </div>
                </div>
                
            </div>
        </div>
    </body>
</html>

<script>
    $(document).ready(function () {
        $(document).on("click", "#pre_lec_minus_button", function () {
            var pre_lec = {};
            pre_lec['subj_id'] = $(this).attr('value');
            $.ajax({
                url:"{% url 'main:pre_lec_delete' %}",
                type: 'POST',
                contentType: 'application/json; charset=utf-8',
                data: JSON.stringify(pre_lec),
                dataType:'text',
                success:function(result){
                    alert("success!");
                    location.reload();
                }
            })
        });
    });

    $(document).ready(function () {
        $(document).on("click", "#save_lec_minus_button", function () {
            var save_lec = {};
            save_lec['subj_id'] = $(this).attr('value');
            $.ajax({
                url:"{% url 'main:save_lec_delete' %}",
                type: 'POST',
                contentType: 'application/json; charset=utf-8',
                data: JSON.stringify(save_lec),
                dataType:'text',
                success:function(result){
                    alert("success!");
                    location.reload();
                }
            })
        });
    });
</script>

main/templates/main/pre_lec_ver2.html
{% load static %}
<html>
    <head>
        <title>COSMIC [class recommender system] 들었던 수업</title>
        <LINK HREF="{% static 'main/css/PreLecVer2.css'%}" rel="stylesheet" />
        <script src="{% static 'main/js/PreLecVer2.js '%}" ></script>
        <script src="{% static 'main/js/jquery-3.5.1.min.js'%}"></script>
        <script src="{% static 'main/js/jquery.csrf.js'%}"></script>
    </head>
    <body>
        <div class="all"> 
            <div class="menu_bar">
                <div class="profile">
                    <div class="profile_logo">
                        <img src="{% static 'main/img/main_logo.png' %}" width="40px" height='40px' >
                    </div>
                    <div class="profile_name">
                        <span style="font-size: 15px; font-weight: bold; ">{{ user.username }}</span><br>
                        <span style="font-size: 10px; font-weight: bold; opacity: 50; ">{{ user.user_number }}</span>
                    </div>
                    <div class="logout">
                        <a href="{% url 'main:logout' %}" >log out</a>
                    </div>
                </div>
        
                <ul class="menu_list" >
                    <li class="menu_button_thisPage" >
                        <A href="{% url 'main:pre_lec_ver2' %}" >
                            <img src="{% static 'main/img/들었던강의.png' %}" width="200" height='40' >
                        </A>
                    </li>
                    <li class="menu_button">
                        <A href="{% url 'main:class_rec_ver2' %}"  >
                            <img src="{% static 'main/img/recommender.png' %}" width="200" height='40' >
                        </A>
                    </li>
                    <li class="menu_button">
                        <A href="{% url 'main:my_class_ver2' %}" >
                            <img src="{% static 'main/img/my_class.png' %}" width="200" height='40' >
                        </A>
                    </li>   
                </ul>
        
            </div>

            <div class="container" >
                <div class="page_title">
                    <span style="font-size: 50px; font-weight: 900; ">들었던 강의</span>
                </div>
                <div class="content_container">
                    {% csrf_token %}
                    <div class="setting_container">
                        <div class="setting_title">
                            <span id='subject'style="font-size: 20px; font-weight: bold; "> 강의 평가</span>
                        </div>
                        <div class="score_window">
                            <span style="font-size: 15px; font-weight: bold; ">학점</span>
                            <br>
                            <select class="score_select">      
                                <option value='4.5'>A+</option>
                                <option value='4.0'>A0</option>
                                <option value='3.5'>B+</option>
                                <option value='3.0'>B0</option>
                                <option value='2.5'>C+</option>
                                <option value='2.0'>C0</option>
                                <option value='1.5'>D+</option>
                                <option value='1.0'>D0</option>
                                <option value='0'>F</option>
                                <option value='4.5'>PASS</option>
                                <option value='0'>FAIL</option>
                            </select>
                            <br>
                        </div>
                        <div class="satisfaction_window">
                            <span style="font-size: 15px; font-weight: bold; ">만족도</span>
                                <br><input type="range" id="good"  min="0" max="100" step="5" value="50"><br>   
                        </div>
                        <div class="keyword_window">
                            <span style="font-size: 15px; font-weight: bold; ">이 수업의 키워드</span><br>
                            <span style="font-size: 15px; font-weight: bold; opacity: 0.5; ">selected</span>
                            <div class="selected_keyword_window">
                                
                            </div>
                            <span style="font-size: 15px; font-weight: bold; opacity: 0.5; ">Unselected</span>
                            <div class="unselected_keyword_window">
                                {% for keyword in keyword_list %}
                                    <div id='unselected_keyword' class="unselected_keyword_button">{{keyword.keyword}}</div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="save_setting_button_window">
                            <div class="save_setting_button"> 
                                <span style="font-size: 15px; font-weight: bold; ">SAVE</span>
                            </div>
                        </div>
                    </div>
                    <div class="search_container">
                        <div class="search_window">
                            <div class="search_title">
                                <span style="font-size: 30px; font-weight: bold; ">Search</span>
                            </div>
                            <form action="" method="get" id="searchForm" name="search">
                                <div class="classTypeFrame">
                                    <input type="text" class="classNameSearch" name="q" size="50" value='{{search}}' placeholder="type class name here"> 
                                    <button class="searchBt" type="submit" > 
                                        <img src="{% static 'main/img/searchbtn.png'%}" width="12" height="12">
                                    </button>
                                </div>
                            </form>
                        </div>
                        {% for subject in subject_list %}
                            <div class="class_window" id='{{ subject.subj_name }}' name='{{ subject.prof_name }}' value='{{ subject.subj_id }}'>
                                <div class="class_name_window">
                                    <span id='subject_name' style="font-size: 2.25rem; font-weight: bold; ">{{ subject.subj_name }} </span><br>
                                    <span style="font-size: 2rem; font-weight: bold; ">{{ subject.prof_name }}</span><br>
                                </div>        
                            </div>
                        {% endfor %}
                      
                    </div>
                </div>
                
            </div>
        </div>
    </body>
</html>

<script>
    $(document).ready(function () {
        $(document).on("click", ".class_window", function () {
            var subject_name = $(this).children('.class_name_window').children('#subject_name').text().trim();
            var subject_id = $(this).attr('value');
            console.log(subject_name);
            console.log(subject_id);
            $('#subject').text('"' + subject_name + '"' + ' 평가');
            $('#subject').attr('value', subject_name);
            $('#subject').attr('name', subject_id);
        });
    });

    $(document).ready(function () {
        $(document).on("click", "#unselected_keyword", function () {
            var keyword = $(this).text();
            $(this).fadeOut();
            $('.selected_keyword_window').append("<div id='selected_keyword' class='selected_keyword_button'>" + keyword + "</div>" );
        });
    });

    $(document).ready(function () {
        $(document).on("click", "#selected_keyword", function () {
            var keyword = $(this).detach();
            $('.unselected_keyword_window').append("<div id='unselected_keyword' class='unselected_keyword_button'>" + keyword.text() + "</div>" );
        });
    });

    $(document).ready(function () {
        $(document).on("click", ".save_setting_button_window", function () {
            var pre_lec = {};
            pre_lec['search'] = $('.classNameSearch').val();
            pre_lec['subject'] = $('#subject').attr('name');
            console.log(pre_lec['subject']);
            pre_lec['rating'] = $(".score_select> option:selected").attr('value');
            pre_lec['good'] = $('#good').val();
            var keyword_list = [];
            var keywords = $('.selected_keyword_window').children('#selected_keyword');
            for(var i=0;i<keywords.length;i++){
                keyword_list = keyword_list.concat(keywords[i].textContent);
            }
            pre_lec['keyword_list'] = keyword_list;
            $.ajax({
                url:"{% url 'main:pre_lec_ver2' %}",
                type: 'POST',
                contentType: 'application/json; charset=utf-8',
                data: JSON.stringify(pre_lec),
                dataType:'text',
                success:function(result){
                    alert("success!");
                    location.reload();
                }
            })
        });
    });


</script>